version: '2'

services:
  coredns:
    image: niusmallnan/coredns:0.9.10-rancher
    network_mode: host
    volumes:
    - ./corefile:/etc/corefile
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m
    command:
    - -conf
    - /etc/corefile
    - -dns.port
    - "53"

  rdns-server:
    images: niusmallnan/rdns-server:v0.2.0
    network_mode: host
    environments:
    - RANCHER_ETCD_ENDPOINTS=http://127.0.0.1:2379
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m

