apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-rdns
  namespace: kube-rdns
data:
  rdns.root_domain: "rancher.io"
  rdns.base_url: "https://api.rdns.rancher.io/v1"
  rdns.renew_duration: "24h"
  rdns.debug: "true"
