apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-rdns-serviceaccount
  namespace: kube-rdns

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-rdns-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - update
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kube-rdns-role
  namespace: kube-rdns
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kube-rdns-role-binding
  namespace: kube-rdns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-rdns-role
subjects:
  - kind: ServiceAccount
    name: kube-rdns-serviceaccount
    namespace: kube-rdns

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-rdns-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-rdns-clusterrole
subjects:
  - kind: ServiceAccount
    name: kube-rdns-serviceaccount
    namespace: kube-rdns
