apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simplelb-without-hostname
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: simplelb-without-hostname.default.zzb88678.w.niusmallnan.com
    http:
      paths:
      - path: /xxx
        backend:
          serviceName: echoheaders-without-hostname
          servicePort: 80
      - path: /yyy
        backend:
          serviceName: echoheaders-without-hostname
          servicePort: 80
