apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simplelb-without-hostname
spec:
  rules:
  - host: simplelb-without-hostname.default.niusmallnan-test.w.rancher.local
    http:
      paths:
      - path: /xxx
        backend:
          serviceName: echoheaders-without-hostname
          servicePort: 80
      - path: /yyy
        backend:
          serviceName: echoheaders-without-hostname
          servicePort: 80
